### ISSUE TITLE
Web site loses my uploaded games if I save in one of them

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#837] opened 2016-01-28 15:46 UTC
I have a number of uploaded games. If I start to play one, and then do SAVE, if I then go to the "Create" all my uploaded game have disappeared! They reappear if I log out and log back in - but now the saved games have disappeared.

I have tried this with two of my games, and the same thing happens. However it does not happen if I save whilst playing someone else's game.

**Comment by alexwarren** [comment] 2016-03-25 14:31
I finally was able to reproduce this consistently and figured out what the problem was. (A long story but the short version is that Microsoft's Entity Framework either sucks or I'm too stupid to figure out how to use it properly). Anyway it should be fixed now.

**Closed by alexwarren** 2016-03-25 14:31 UTC
